### ISSUE TITLE
Day Yield sensor suddenly stoped working

### ISSUE THREAD

**Issue by thomashogema** [coen800/pysolarfrontier#3]
Hi @coen800,

Afgelopen maand draaide de integratie perfect, tot 18 mei. Alle data vanaf die dag is incorrect. De `solar_frontier_today_yield` lijkt nooit naar 0 te resetten. Er is slechts één meetpunt beschikbaar wat te laag of zelfs negatieve waardes aangeeft. De month en year yield lopen wel netjes op. Enig idee waar dit aan ligt, of ideeën voor een fix?

Deze error staat in de logs en zou gerelateerd kunnen zijn, maar de trace geeft niks aan over pysolarfrontier:
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:403
First occurred: June 5, 2023 at 7:04:18 PM (2 occurrences)
Last logged: 9:56:00 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'

```

**Screenshots**
Productie maand mei
![image](https://github.com/coen800/pysolarfrontier/assets/15984767/60ace81f-a955-41c9-b34c-0964167e566f)

Productie 17 mei
![image](https://github.com/coen800/pysolarfrontier/assets/15984767/33655860-1ad1-43e7-9825-154088289df6)

Productie 18 mei
![image](https://github.com/coen800/pysolarfrontier/assets/15984767/977c0586-0c9b-4a46-bd0a-779e8132ef46)

Productie 19 mei
![image](https://github.com/coen800/pysolarfrontier/assets/15984767/97a93196-1e20-4a27-8451-ccf884a645b2)

**Doorlopen teststappen**
* Herstart Home Assistant
* Update Home Assistant
* Check beschikbaarheid Solar Frontier omvormer
* Gecheckt of de integratie draait en waardes ontvangt
* Waardes in statistiek tabellen opgezocht om waardes te cross checken, kloppen niet meer vanaf 18 mei

Als je verder nog suggesties hebt hoor ik het graag!

**Comment by coen800** [comment]
Je hebt de troubleshooting stappen die ik zou voorstellen al gedaan. Enige wat ik mij kan bedenken is dat ik mijn installatie nog niet hebt geupgrade naar de laatste versie. Ik draai nog op 2023.4.4, wellicht dat er breaking changes zijn geweest, ik heb de laatste tijd niet veel gekeken naar de laatste updates dus ik zou het niet weten.

**Comment by thomashogema** [comment]
Had geen updates van HA uitgevoerd rond die periode, daarom was ik vooral verbaasd.

Heb als volgende stappen de integratie een 'uit en ingeschakeld', mogelijk dat wisselen naar month_yield ook een oplossing biedt aangezien die wel normaal oploopt.

**Comment by thomashogema** [comment]
Update: heb mijn consumptie sensor aangepast naar de month_yield en die werkt nog wel netjes. Historische gegevens zijn ook weer correct.
![image](https://github.com/coen800/pysolarfrontier/assets/15984767/984ad387-a10f-4850-b2b2-da952d07646b)

Geen idee waarom de day_yield gesneuveld is, maar ik ben weer blij :)
